# Generated by Django 5.1.4 on 2026-02-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=80)),
                ('userName', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('phoneNo', models.CharField(max_length=80)),
                ('image', models.FileField(default=True, max_length=259, null=True, upload_to='contactForm/')),
            ],
        ),
    ]
