# Generated by Django 5.1.4 on 2026-02-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactForm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='phoneNo',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='userName',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='image',
            field=models.FileField(max_length=259, null=True, upload_to='contactForm/'),
        ),
    ]
